name: Weather App CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./weather-app  # applies to all run steps below

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'  # built-in caching for npm dependencies
          cache-dependency-path: weather-app/package-lock.json
      - name: Install dependencies
        run: npm ci

      - name: Lint the code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Upload test results
        if: always()  # ensures test results are uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./weather-app/test-results/
